seed: 1024
data:
    dataset: ucf101
    modality: RGB
    num_segments: 8
    seg_length: 1
    batch_size: 32
    workers: 8
    num_classes: 101
    image_tmpl: 'image_{:04d}.jpg'
    val_root: '/nfs/wattrel/data/md0/datasets/state_aware/ucf101_images'
    val_list: 'lists/ucf101/ucf_full_for_zeroshot.txt' #
    label_list: 'lists/ucf101/ucf_labels.csv'
    index_bias: 1
    input_size: 224
network:
    arch: ViT-L/14
    init: True
    drop_out: 0.0
    emb_dropout: 0.0 
    sim_header: Transf
    interaction: DP  # DP VCS
logging:
    print_freq: 10
    eval_freq: 1