pretrain: "./exp/clip_ucf/ViT-B/16/gtea/20211117_003329/last_model.pt"
seed: 1024
data:
    dataset: gtea
    modality: RGB
    num_frames: 15
    seg_length: 1
    split: 2
    batch_size: 1
    workers: 8
    gpus: 1
    num_classes: 74
    index_bias: 1
    input_size: 224
    save_dir: ''
    randaug:
        N: 0 #2
        M: 0  #9
network:
    arch: ViT-B/16
    init: True # scratch, imagenet, kinetics
    drop_out: 0.0 # probability of an element to be zeroed
    emb_dropout: 0.0 # probability of embedding to be zeroed
    if_proj: False
    partial_bn: False
    version: ''
    bn_momentum: 0.1
    consensus_type: avg
    type: clip_ucf
    sim_header: "Transf"   #Transf   meanP  LSTM Conv_1D Transf_cls
    fix_text: False
    fix_img: False
    describe:
logging:
    print_freq: 10
    eval_freq: 1
